const exhibitionPlace = [
  { id: 0, name: '모든 지역', value: 'ALL' },
  { id: 1, name: '서울', value: 'SEOUL' },
  { id: 2, name: '경기', value: 'GYEONGGI' },
  { id: 3, name: '인천', value: 'INCHEON' },
  { id: 4, name: '강원', value: 'GANGWON' },
  { id: 5, name: '부산', value: 'BUSAN' },
  { id: 6, name: '대구', value: 'DAEGU' },
  { id: 7, name: '대전', value: 'DAEJEON' },
  { id: 8, name: '광주', value: 'GWANGJU' },
  { id: 9, name: '울산', value: 'ULSAN' },
  { id: 10, name: '세종', value: 'SEJONG' },
  { id: 11, name: '충북', value: 'CHUNGBUK' },
  { id: 12, name: '충남', value: 'CHUNGNAM' },
  { id: 13, name: '전북', value: 'JEONBUK' },
  { id: 14, name: '전남', value: 'JEONNAM' },
  { id: 15, name: '경북', value: 'GYEONGBUK' },
  { id: 16, name: '경남', value: 'GYEONGNAM' },
  { id: 17, name: '제주', value: 'JEJU' },
];
export default exhibitionPlace;
