import ExhibitionCard from 'components/molecule/ExhibitionCard';
import SwiperWrapper from 'components/organism/Swiper';
import SwiperContainer from 'components/organism/SwiperContainer';
import type { NextPage } from 'next';
import React, { useState } from 'react';

const Home: NextPage = () => {
  //TODO : 맞춤전시회로 이동해야함
  const [selectedArea, setSelectedArea] = useState([]);
  const [selectedPeriod, setSelectedPeriod] = useState([]);

  return (
    <div>
      <SwiperContainer title="다가오는 전시회" type="upcoming">
        <SwiperWrapper
          items={[
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={true}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={false}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={false}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
          ]}
        />
      </SwiperContainer>

      <SwiperContainer title="인기많은 전시회" type="popular">
        <SwiperWrapper
          items={[
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
            <ExhibitionCard
              exhibitionId={ret.exhibitionId}
              name={ret.name}
              thumbnail={ret.thumbnail}
              startDate={ret.startDate}
              endDate={ret.endDate}
              likeCount={ret.likeCount}
              reviewCount={ret.reviews.length}
              isLiked={ret.isLiked}
              key={ret.exhibitionId}
            />,
          ]}
        />
      </SwiperContainer>
    </div>
  );
};

export default Home;
